version: "3"

services:
  mongoconnection:
    environment:
      - SECRET=admin
    build:
      context: ./mongoConnection
      dockerfile: Dockerfile
    container_name: mongoConnection
    ports:
      - 1234:8080
    links:
      - db
  trakiencustomerapi:
    environment:
      - SECRET=admin
    build:
      context: ./trakienCustomerAPI
      dockerfile: Dockerfile
    container_name: trakiencustomerAPI
    ports:
      - 81:8080
    links:
      - db
  apiupdater:
    environment:
      - SECRET=admin
    build:
      context: ./apiUpdater
      dockerfile: Dockerfile
    container_name: apiUpdater
    ports:
      - 4999:8080
    links:
      - db
      - webscraper
  productapi:
    environment:
      - SECRET=admin
    build:
      context: ./productApi
      dockerfile: Dockerfile
    container_name: productApi
    ports:
      - 4599:8080
    links:
      - db
  webscraper:
    environment:
      - FLASK_APP=WebScrapingKKK.py
      - FLASK_DEBUG=1
    build:
      context: ./webScraper
      dockerfile: Dockerfile
    container_name: webScraper
    ports:
      - 5000:5000
    links:
      - db
  db:
    image: mongo:latest
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    command: mongod
volumes:
  mongodb:
  mongodb_config:
